### PR TITLE
Adding additional versions

### PR DESCRIPTION
**Pull request by flcdrg**
- Support new 'sdks' array

Implements #43

FYI this will cause the following additional packages to be updated:

- dotnetcore-sdk.2.1.202.nupkg
- dotnetcore-sdk.2.1.508.nupkg
- dotnetcore-sdk.2.1.605.nupkg
- dotnetcore-sdk.2.2.108.nupkg
- dotnetcore-sdk.2.2.205.nupkg

### CODE REVIEW

**Comment by flcdrg** [comment]
Just hold off on merging this. It appears the checksums for for 2.1.202 are incorrect - chasing up with Microsoft as to why they're different.

**Comment by flcdrg** [comment]
Wait until https://github.com/dotnet/core/issues/3250 is resolved

**Comment by flcdrg** [comment]
Should be good to go now. The 2.0 releases.json file has been fixed

**Comment by riezebosch** [comment]
Merged with https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/commit/719b12ab68f78c993ac76b1b76f8b6865112d245

**Pull request closed without merging**
