### PR TITLE
Fixed 3.1.0 links;

### PR DESCRIPTION
**Pull request by Heteroculturalism**

### CODE REVIEW

**Comment by riezebosch** [comment]
See: #47

**Comment by riezebosch** [comment]
The update process is automated so I'd rather see Microsoft fix in the `releases.json`.

**Comment by Heteroculturalism** [comment]
Is Microsoft aware of the releases.json issue? What about people who already downloaded the Chocolateky package? Will a new version be published with a date timestamp in the version number (eg 3.1.0.20191205)?

**Comment by Heteroculturalism** [comment]
Thoughts?

**Comment by riezebosch** [comment]
https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/issues/47#issuecomment-563203870

**Pull request closed without merging**
