### PR TITLE
.NET Core 2.0.6

### PR DESCRIPTION
**Pull request by martincostello**
Update for [.NET Core 2.0.6](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.6-download.md).

### CODE REVIEW

**Comment by martincostello** [comment]
I just checked on the [build](https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages/build/245), and it doesn't appear to have published the packages. Would you be able to do that manually this morning? I'd like to prep some AMIs using the new packages for deployment on Monday.

**Comment by martincostello** [comment]
Sorry to chase, but it looks like the [push attempt failed](https://ci.appveyor.com/project/riezebosch/dotnetcore-chocolateypackages#L140) despite the AppVeyor build being marked as successful.

**Comment by riezebosch** [comment]
[Exactly](https://github.com/majkinetor/au/issues/135).

**Comment by riezebosch** [comment]
Okay, manual it is. Let me know if there's still anything missing.

**Comment by martincostello** [comment]
Awesome, thank you! 😃

**Pull request merged**
