### PR TITLE
Long Term Support (v1.1.4)

### LINKED ISSUE #16: Long Term Support (v1.1.4)
I need packages for LTS 1.1.4. I'm happy to make them and submit a PR, but this repo is "latest" only. Should I push a branch for review and, if OK, we can publish packages from that branch and then delete it?

https://www.microsoft.com/net/download/windows

### PR DESCRIPTION
**Pull request by AnthonyMastrean**
This should fix #16 for the dotnetcore packages in this repository. I should do the same for the [dotnetcore-sdk](https://github.com/riezebosch/BoxstarterPackages/) packages.

I'll leave it up to you how you want to pull this branch over (probably add a remote, fetch, and checkout the remote branch as a local branch, then push). This branch was created from what appeared to be the last commit for 1.1.2, before all of the changes for 2.0.0 (3e992e8b85485d898aa77cd98f5aa6ff1a39d287).

### CODE REVIEW

**Comment by riezebosch** [comment]
Won't it make more sense to place the LTS in a separate folder so we can maintain both independently?

**Comment by AnthonyMastrean** [comment]
It's "just" a version of `dotnetcore`, but we should probably create a `dotnetcore-lts` that points at the specific version of `dotnetcore`.

**Comment by AnthonyMastrean** [comment]
OK, maybe I went a little overboard, but it seemed like we needed an "lts" package pointing to the regular package w/ a fixed version for every kind of package, because I didn't want to decide if folks wanted an "install" or "portable" package.

| lts | regular | version |
|----|---------|---------|
| dotnetcore-lts | dotnetcore | 1.1.4
| dotnetcore-lts-runtime | dotnetcore-runtime | 1.1.4 |
| dotnetcore-lts-runtime.install | dotnetcore-runtime.install | 1.1.4 |
| dotnetcore-lts-runtime.portable | dotnetcore-runtime.portable | 1.1.4 |

**Comment by riezebosch** [comment]
Do you still think this is relevant as it seems Microsoft [has dropped the term lts](https://www.microsoft.com/net/download/all)? With the recent introduction of package automation and streams we are already publishing updates for all supported releases.

**Comment by jberezanski** [comment]
@riezebosch Yes, Microsoft has adopted the practice of updating several major.minor branches independently and the "lts" term is no longer meaningful.

And yes, thanks to the automation, all of those branches receive updated packages on chocolatey.org.

One problem still remains, however. There is currently no easy way for the user to configure Chocolatey to remain on a single dotnetcore branch (for example, 1.1) during package upgrades. The [`pin` command](https://chocolatey.org/docs/commands-pin) accepts a single version only, so one can, for example, pin dotnetcore-runtime.install to version 1.1.7 to prevent `choco upgrade all` from installing 2.x, but it will at the same time prevent choco from installing 1.1.8 or any later update from the 1.1 branch.

There is an open feature request (https://github.com/chocolatey/choco/issues/1278) which would enable support for exactly this scenario, so ultimately the problem will disappear.

A workaround [suggested](https://github.com/chocolatey/choco/issues/1278#issuecomment-298332487) by @ferventcoder was to create a metapackage which would depend on a range of versions of the package in question, effectively pinning that package to that version range. We could actually build such packages for all dotnetcore branches - they would be a one-time effort (so no maintenance burden for us) and users could use them until the pin-to-range feature is implemented in choco.

**Comment by ferventcoder** [comment]
One could also use the side by side feature if necessary. It just doesn't provide upgrade support of packages. Here's a fantastic article talking about this at https://www.phillipsj.net/posts/managing-multiple-versions-of-terraform-with-chocolatey

**Pull request closed without merging**
