### PR TITLE
Install both 64-bit and 32-bit runtimes and package stores on 64-bit systems

### PR DESCRIPTION
**Pull request by jberezanski**
Implements #14

### CODE REVIEW

**Comment by riezebosch** [comment]
I think it would be better to turn this around: opt-in for installing for both architectures. This reduces the complexity of the package because you don't have to check the environment but just leave it up to the user if installing both versions is applicable. It is more in line with the deployment of Microsoft providing us with two separate installers instead of installing both versions from the same installer. And lastly the `choco upgrade` process is perhaps now more complicated when installing both versions but less complicated if you only want one. Your thoughts?

**Comment by jberezanski** [comment]
One scenario where opt-in will not work is dependencies.

Let's consider a .NET Core application which needs to be 32-bit, for whatever reason (perhaps it uses a native DLL which exists only as 32-bit). The developer creates a Chocolatey package for it, adding a dependency on dotnetcore-runtime. However, the dependency syntax in nuspec does not support passing parameters, so the developer cannot specify that the 32-bit runtime is needed even on a 64-bit system and the dependency will not work as expected. Even though both packages install successfully, the app does not run.

We could attempt to handle this scenario by publishing separate packages for x86 and x64 (aligning perfectly with the native installers), but that in turn would make it impossible to specify correct dependencies for AnyCPU apps (such an app would need to say "I depend on this package on x86 and on that other package on x64" - again, not supported in nuspec).

I see dependencies as the most common use case for runtime/framework packages, so in my opinion all scenarios should work. I don't expect regular users to care about runtimes or install them manually. The goal of Chocolatey is to make installing software on Windows easier, so I'd like to be able to tell my less technical friends simply to "cinst appX" without having to instruct them how to install the runtime package, taking care to provide additional parameters. And the tech-savvy users with specific needs would have no problem opting out of x86 if they needed it.

By the way, there was a similar discussion regarding the [vcredist2013 package](https://chocolatey.org/packages/vcredist2013). The agreed-upon consensus was to install both runtimes by default.

**Comment by riezebosch** [comment]
Uninstallation doesn't work because multiple keys are found.

**Comment by riezebosch** [comment]
@jberezanski Could you review the rebase and new commit I made? Please confirm that there should be no uninstall script for the aspnetcore-runtimepackagestore.

**Comment by jberezanski** [comment]
There were still conflicts, so I rebased again.

> Please confirm that there should be no uninstall script for the aspnetcore-runtimepackagestore.

Yes, that is correct. .NET Core installers use Windows Installer, so the Chocolatey Auto Uninstaller is easily able to uninstall the software in a robust and predictable way. This makes our (brittle) uninstall scripts unnecessary. In fact, I have just removed the uninstall script for the runtime package as well.

I have also improved the checksum calculation code in the same way I had done earlier for the windowshosting and runtimepackagestore packages.

I am now in the process of testing the runtime and runtimepackagestore packages.

**Comment by jberezanski** [comment]
I believe it is good to go.

**Pull request merged**
